/* 
 * File:   main.cpp
 * Author: WeikangDu
 * Created on September 25, 2016, 12:35 PM
 * Purpose: Calculate for the income of Stadium Seating
 */

#include <iostream>
#include <iomanip>

using namespace std;

/*
 * 
 */
int main(int argc, char** argv) {
    
   //Declaration Variables
    float   priceA = 15.00f, // The price of class A seat is $ 15.
            priceB = 12.00f, // The price of class B seat is $ 12.
            priceC = 9.00f;  // The price of class C seat is $ 9.
    int   numA, numB, numC; //The number of class A seats were sold
                            //The number of class B seats were sold
                            //The number of class C seats were sold
    float incom;           //The amount of income generated by tickets
    
    //Input
    cout<<"How many tickets were sold for class A seats?\n";
    cin>>numA;
    
    cout<<"How many tickets were sold for class B seats?\n";
    cin>>numB;
    
    cout<<"How many tickets were sold for class C seats?\n";
    cin>>numC;
    
    incom = priceA*numA + priceB*numB + priceC*numC;//Total income
    
    
    
    //Display output
    cout<<"The Stadium Seating Price:\n";
    cout<<"Class A, Class B, Class C\n";
    cout<<setprecision(2)<<fixed<<showpoint<<priceA<<" $"<<", "<<
          setprecision(2)<<fixed<<showpoint<<priceB<<" $"<<",  "<<
          setprecision(2)<<fixed<<showpoint<<priceC<<" $"<<endl;
    
    cout<<"The Stadium sold "<<endl;
    cout<<numA<<" seats for class A;\n";
    cout<<numB<<" seats for class B;\n";
    cout<<numC<<" seats for class C.\n";
    cout<<"The amount of income generated from tickets is "<<
            setprecision(2)<<fixed<<incom<<" $"<<endl;
    
    

    return 0;
}

